modLoader = "javafml"
loaderVersion = "[40,)"
license = "CC-BY-NC-ND-4.0"
issueTrackerURL = "https://github.com/Faboslav/friends-and-foes/issues"

[[mods]]
modId = "friendsandfoes"
version = "${modVersion}"
displayName = "${modName}"
authors = "${modAuthor}"
description = "${modDescription}"
logoFile = "icon.jpg"

[[dependencies.friendsandfoes]]
modId = "forge"
mandatory = true
versionRange = "[44.0.18,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.friendsandfoes]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.3,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.friendsandfoes]]
modId = "cloth_config"
mandatory = false
versionRange = "[7,)"
ordering = "NONE"
side = "CLIENT"
